//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class About
    {
        public int AboutId { get; set; }
        public string AboutUs { get; set; }
        public byte[] AboutImg { get; set; }
        public string AboutDetails { get; set; }
    }
}
